# https://ithelp.ithome.com.tw/articles/10251471
services:

  flask:
    build: ./flask
    container_name: flask_container
    # restart: always
    environment:
      - APP_NAME=PointCloudApp
    expose:
      - 8888


  nginx:
    build: ./nginx
    container_name: nginx_container
    # restart: always
    ports:
      - "80:80"
    # 先啟動flask的container，再啟動nginx的container
    depends_on:
      - flask
