name: Flask CICD

# 觸發條件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 執行一項或多項任務
jobs: 
  
  Stop-Containers:
    runs-on: self-hosted
    steps:
    - name: where am i
      run: |
        pwd
        ls
    # - uses: actions/checkout@v2
    #遠端部署
    - name: where am i
      run: |
        pwd
        ls
    - name: stop nginx container
      run: 
        docker container stop $(docker container ls -q --filter name=nginx_container)
    - name: stop flask container
      if: always()
      run:
        docker container stop $(docker container ls -q --filter name=flask_container)
    - name: prune containers
      if: always()
      run:
        docker container prune -f
  CD:
    runs-on: self-hosted
    needs: Stop-Containers
    if: always()
    steps:
    - uses: actions/checkout@v2
    # auto git clone https://github.com/yam8572/PointCloudApi.git
    - name: where am I
      run:
        pwd 
      # defaut: C:\www\actions-runner\_work\PointCloudApi\PointCloudApi

    - name: docker compose up 
      run:
        # -d: 在後台執行該服務
        docker-compose up -d --build
    
    - name: remove project after docker build complete
      run: |
        cd ..
        pwd 
        ls
    #    rm -force PointCloudApi
    #    ls
        
    # - name: remove project folder
    #   run: |
    #     cd ..
    #     pwd
    #     ls
    #     rm -force code
    
# if: always()>> always execute, and returns true, even when canceled.
