name: Flask CICD

# 觸發條件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 執行一項或多項任務
jobs: 
  Stop-Containers:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    # 遠端部署
    - name: stop nginx container
      run: 
        docker container stop $(docker container ls -q --filter name=nginx_container)
    - name: stop flask container
      if: always()
      run:
        docker container stop $(docker container ls -q --filter name=flask_container)
    - name: prune containers
      if: always()
      run:
        docker container prune -f
  CD:
    runs-on: self-hosted
    needs: Stop-Containers
    if: always()
    steps:
    - name: where am I
      run:
        pwd
#     - name: set workdir
#       run: |
#         working-directory: C:\www
    - name: route to code folder
      run:
        pwd
    - name: clone source code
      run:
        git clone https://github.com/yam8572/PointCloudApi.git
    - name: where am I
      run:
        pwd
#     - name: route to project
#       run:
#         cd ./PointCloudApi
#     - name: docker compose up 
#       run:
#         docker-compose up -d --build
#     - name: route back
#       run:
#         cd .. 
#     - name: remove project folder
#       run:
#         rm -rf flask_container
    
# if: always()>> always execute, and returns true, even when canceled.
